## NumPy

In [1]:
import numpy as np

In [2]:
#You can create an empty NumPy array as follows:
empty_array = np.array(object = [])

In [3]:
#Note that the default data type for an empty array is float64 or a 64-bit, double-precision floating point, which is the same as we’ve been using while defining floats.
#The type() function on an array would give us the following:  

type(empty_array)

numpy.ndarray

The type() function on an array would give us the numpy.ndarray

To find the data type of the elements within the array, we can use the .dtype attribute:

Other useful attributes are .ndim which records the number of dimensions of the array, 
.shape which records its shape (i.e., number of elements in each dimension), 
and .size which records the total number of elements across all dimensions of the array.

In [7]:
#We can create a NumPy array with elements as follows:
my_array = np.array([1,2,3])# this would be of dtype int64
print(my_array.dtype)
my_array

int64


array([1, 2, 3])

In [8]:
#Arrays of different data types are automatically typecast if possible:
my_array = np.array([1.5, 2, 3])  # this would be of dtype float64
print(my_array.dtype)

float64


In [9]:
#There are various other ways to create arrays
print(np.array(range(1, 10)))
print(np.arange(1, 10) )

#If you want an array of zeroes, you could use np.zeros() as follows:
print(np.zeros(shape = 10))

#If you’d rather have integer zeroes, you could specify the dtype parameter:
print(np.zeros(shape = 10, dtype= 'int'))


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [10]:
#Similarly, you could get ones with the np.ones() function:
print(np.ones(shape = 10, dtype= 'int'))
print(np.ones(shape = 10))

[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
#The np.linspace() function lets you create an array containing as many elements as you’d like between a start and a stop point. Note that the stop is inclusive in this case:
np.linspace(start = 2, stop = 2.5, num = 5) 

array([2.   , 2.125, 2.25 , 2.375, 2.5  ])

In [15]:
#We can also create multidimensional NumPy arrays:

np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### NumPy Arrays - Indexing and slicing Arrays

In [17]:
#NumPy allows accessing elements in an array using indices. The indexing follows zero-based numbering.

#1D Array Indexing


arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # Output: 10
print(arr[2])   # Output: 30
print(arr[-1])  # Output: 50 (last element)

10
30
50


In [18]:
#2D Array Indexing

arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print(arr2d[0, 0])  # Output: 1 (row 0, col 0)
print(arr2d[1, 2])  # Output: 6 (row 1, col 2)
print(arr2d[-1, -1])  # Output: 9 (last row, last column)

1
6
9


In [19]:
#3D indexing
arr3d = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])

print(arr3d[0, 1, 1])  # Output: 4 (First matrix, second row, second column)

4


2. Slicing NumPy Arrays
Slicing allows extracting portions of arrays using the syntax:
arr[start:stop:step]

In [20]:
#1d slicing 
arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])   # Output: [20 30 40]  (From index 1 to 3)
print(arr[:3])    # Output: [10 20 30]  (First 3 elements)
print(arr[2:])    # Output: [30 40 50 60] (From index 2 to end)
print(arr[::2])   # Output: [10 30 50] (Every second element)
print(arr[::-1])  # Output: [60 50 40 30 20 10] (Reverse array)

[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [21]:
#2d slicing

arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

print(arr2d[:2, 1:3]) 

[[2 3]
 [6 7]]


In [22]:
#Boolean Indexing
#Boolean conditions can be used to filter arrays.

arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])  
# Output: [30 40 50]

even_mask = arr % 20 == 0
print(arr[even_mask])  
# Output: [20 40]

[30 40 50]
[20 40]


In [23]:
#Fancy Indexing (Using Lists or Arrays)
arr = np.array([10, 20, 30, 40, 50])

print(arr[[1, 3, 4]])  
# Output: [20 40 50]

[20 40 50]


In [24]:
# np.where(x,y,z) can also be used to filter for values from a np array based on a given condition. 
# x = condition arr % 3 == 0, y = value if true (arr), z = value if false (0 or np.nan)

np.where(arr % 3 == 0, arr, 0)


array([ 0,  0, 30,  0,  0])

### NumPy Arrays - Array Manipulations

In [27]:
arr = np.array([1, 2, 3, 4, 5])
#You can add an element to the end of this array by using np.append(), as follows:
arr = np.append(arr = arr, values = 6)  # arr is modified to array([1, 2, 3, 4, 5, 6])
#Notice how this operation doesn’t occur in-place. You would have to reassign the output to a variable (arr again in this case) for the changes to stick.
arr 

array([1, 2, 3, 4, 5, 6])

In [28]:
#Similarly, there are other functions like np.delete(), np.transpose(), np.concatenate(), and so forth. You can read about all the available array manipulation functions here. Their uses are fairly intuitive and tend to expand on existing functions from the base library. For instance, you can concatenate multiple arrays at once:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.array([7, 8, 9])

np.concatenate([arr1, arr2, arr3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#Note that when you are using these functions on multidimensional arrays, you can specify the axis parameter to specify which dimensions to perform the operations on. For instance:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6]])
mat3 = np.array([[7], [8]])
np.concatenate((mat1, mat2), axis = 0) #axis = 0 for rows 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((mat1, mat3), axis = 1) #axis = 1 for columns

array([[1, 2, 7],
       [3, 4, 8]])

In [31]:
#Notice how the dimensions must match for these operations to work as intended.