A **NumPy array** and a **Python list** might seem similar, but they have key differences in terms of performance, functionality, and behavior.  

### **1. Performance & Speed** 🚀  
- **NumPy arrays** are **faster** than lists because they use **contiguous memory** and **vectorized operations**.  
- **Lists** store elements in different memory locations, making operations **slower**.  

🔹 **Example:** Squaring numbers in a list vs a NumPy array  
```python
import numpy as np
import time

lst = list(range(1_000_000))
arr = np.array(lst)

# List computation
start = time.time()
lst_squared = [x**2 for x in lst]
print("List time:", time.time() - start)

# NumPy computation
start = time.time()
arr_squared = arr ** 2  # Vectorized operation
print("NumPy time:", time.time() - start)
```
**Result:** NumPy is **much faster** 🚀  

---

### **2. Memory Efficiency 📦**  
- **NumPy arrays** use **less memory** because they store elements of the **same data type** (`int32`, `float64`, etc.).  
- **Lists** store objects with **additional metadata**, making them **memory-heavy**.  

🔹 **Example:** Checking memory size  
```python
import sys
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

print("List size:", sys.getsizeof(lst))    # More memory usage
print("NumPy array size:", arr.nbytes)  # Less memory usage
```
**Result:** NumPy arrays consume **less memory** than lists.  

---

### **3. Type Consistency**  
- **NumPy arrays** enforce a **single data type** (`int`, `float`, `bool`, etc.).  
- **Lists** can have **mixed types** (e.g., `[1, "hello", 3.14]`).  

🔹 **Example:**  
```python
arr = np.array([1, 2, 3.5])
print(arr)  # Output: [1. 2. 3.5] -> All converted to float
```
NumPy **automatically converts** types for efficiency.

---

### **4. Built-in Mathematical Operations 🧮**  
- **NumPy arrays** support **vectorized operations** (`+, -, *, /`) directly.  
- **Lists** require explicit looping or list comprehensions.  

🔹 **Example: Adding 10 to all elements**  
```python
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

# List approach
lst_plus_10 = [x + 10 for x in lst]

# NumPy approach (faster!)
arr_plus_10 = arr + 10
```
NumPy is **cleaner and more efficient** ✅  

---

### **5. Multi-dimensional Support 📊**  
- **NumPy arrays** support **multi-dimensional arrays** (matrices, tensors).  
- **Lists** require nested lists, making indexing & computation cumbersome.  

🔹 **Example: Creating a 2D array**  
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Easy with NumPy
print(arr.shape)  # Output: (2,3)
```
With lists, you’d have to manually handle indexing, leading to **complexity**.  

---

### **When to Use What?**  
| Feature        | NumPy Array ✅ | Python List ❌ |
|---------------|--------------|---------------|
| Performance   | Fast 🚀 | Slow 🐢 |
| Memory Usage  | Efficient 📦 | More overhead |
| Math Operations | Built-in 🧮 | Manual looping required 🔄 |
| Multi-Dimensional Support | Yes ✅ | No (nested lists needed) ❌ |
| Type Consistency | Enforced 🔢 | Mixed types allowed ✅ |

### **Conclusion**  
- Use **NumPy arrays** when working with **large numerical datasets, machine learning, and data science**.  
- Use **Python lists** for **general-purpose programming and flexibility**.  



In [1]:
import numpy as np

In [3]:
list = [1,2,3]
print(list)
arr = np.array(list) # convert a list to a numpy array
print(arr)

[1, 2, 3]
[1 2 3]


In [5]:
# 2d array
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
print(list_2d)
arr_2d = np.array(list_2d)
print(arr_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#creating a numpy array with arange function
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#if want to jump to every 2nd digit in the arange function
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
#if want special types of NumPy array - such as all with 0 or 1, then:
np.zeros (3) #generates a numpy arry with all 0 float values of 3 length

array([0., 0., 0.])

In [9]:
#if want a multi-dim array then insted of 3 like in above, pass a tupel 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#similarly ones 
np.ones(5)
#np.twos(5) this does not work

array([1., 1., 1., 1., 1.])

In [13]:
#linspace funtion to generate a numpy array with evenly spaced numbers between a specified range
np.linspace(0,10,6) # this returns a numpy array starting at 0, ending at 10, with evenly spaced 6 numbers in between

array([ 0.,  2.,  4.,  6.,  8., 10.])