A **NumPy array** and a **Python list** might seem similar, but they have key differences in terms of performance, functionality, and behavior.  

### **1. Performance & Speed** 🚀  
- **NumPy arrays** are **faster** than lists because they use **contiguous memory** and **vectorized operations**.  
- **Lists** store elements in different memory locations, making operations **slower**.  

🔹 **Example:** Squaring numbers in a list vs a NumPy array  
```python
import numpy as np
import time

lst = list(range(1_000_000))
arr = np.array(lst)

# List computation
start = time.time()
lst_squared = [x**2 for x in lst]
print("List time:", time.time() - start)

# NumPy computation
start = time.time()
arr_squared = arr ** 2  # Vectorized operation
print("NumPy time:", time.time() - start)
```
**Result:** NumPy is **much faster** 🚀  

---

### **2. Memory Efficiency 📦**  
- **NumPy arrays** use **less memory** because they store elements of the **same data type** (`int32`, `float64`, etc.).  
- **Lists** store objects with **additional metadata**, making them **memory-heavy**.  

🔹 **Example:** Checking memory size  
```python
import sys
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

print("List size:", sys.getsizeof(lst))    # More memory usage
print("NumPy array size:", arr.nbytes)  # Less memory usage
```
**Result:** NumPy arrays consume **less memory** than lists.  

---

### **3. Type Consistency**  
- **NumPy arrays** enforce a **single data type** (`int`, `float`, `bool`, etc.).  
- **Lists** can have **mixed types** (e.g., `[1, "hello", 3.14]`).  

🔹 **Example:**  
```python
arr = np.array([1, 2, 3.5])
print(arr)  # Output: [1. 2. 3.5] -> All converted to float
```
NumPy **automatically converts** types for efficiency.

---

### **4. Built-in Mathematical Operations 🧮**  
- **NumPy arrays** support **vectorized operations** (`+, -, *, /`) directly.  
- **Lists** require explicit looping or list comprehensions.  

🔹 **Example: Adding 10 to all elements**  
```python
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)

# List approach
lst_plus_10 = [x + 10 for x in lst]

# NumPy approach (faster!)
arr_plus_10 = arr + 10
```
NumPy is **cleaner and more efficient** ✅  

---

### **5. Multi-dimensional Support 📊**  
- **NumPy arrays** support **multi-dimensional arrays** (matrices, tensors).  
- **Lists** require nested lists, making indexing & computation cumbersome.  

🔹 **Example: Creating a 2D array**  
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Easy with NumPy
print(arr.shape)  # Output: (2,3)
```
With lists, you’d have to manually handle indexing, leading to **complexity**.  

---

### **When to Use What?**  
| Feature        | NumPy Array ✅ | Python List ❌ |
|---------------|--------------|---------------|
| Performance   | Fast 🚀 | Slow 🐢 |
| Memory Usage  | Efficient 📦 | More overhead |
| Math Operations | Built-in 🧮 | Manual looping required 🔄 |
| Multi-Dimensional Support | Yes ✅ | No (nested lists needed) ❌ |
| Type Consistency | Enforced 🔢 | Mixed types allowed ✅ |

### **Conclusion**  
- Use **NumPy arrays** when working with **large numerical datasets, machine learning, and data science**.  
- Use **Python lists** for **general-purpose programming and flexibility**.  



In [1]:
import numpy as np

In [3]:
list = [1,2,3]
print(list)
arr = np.array(list) # convert a list to a numpy array
print(arr)

[1, 2, 3]
[1 2 3]


In [5]:
# 2d array
list_2d = [[1,2,3],[4,5,6],[7,8,9]]
print(list_2d)
arr_2d = np.array(list_2d)
print(arr_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#creating a numpy array with arange function
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#if want to jump to every 2nd digit in the arange function
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
#if want special types of NumPy array - such as all with 0 or 1, then:
np.zeros (3) #generates a numpy arry with all 0 float values of 3 length

array([0., 0., 0.])

In [9]:
#if want a multi-dim array then insted of 3 like in above, pass a tupel 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#similarly ones 
np.ones(5)
#np.twos(5) this does not work

array([1., 1., 1., 1., 1.])

In [13]:
#linspace funtion to generate a numpy array with evenly spaced numbers between a specified range
np.linspace(0,10,6) # this returns a numpy array starting at 0, ending at 10, with evenly spaced 6 numbers in between

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
# use 'eye(n)' function to create a nxn identiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# to create an array with 'n' random numbers with values between 0-1 use np.ramdon.rand()
np.random.rand(5)
# for gaussian distribution centered around 0:
np.random.randn(5)

# for such 2 dim array with random numbers, just add n,m:
np.random.rand(4,5)

array([[0.10283535, 0.62292816, 0.06155714, 0.50463762, 0.00713049],
       [0.47950347, 0.48308753, 0.80139384, 0.22571161, 0.07213066],
       [0.45301642, 0.30577531, 0.2408306 , 0.42758257, 0.36633027],
       [0.69114154, 0.86078731, 0.01584519, 0.25530143, 0.32226312]])

In [21]:
# for 20 integer array from start 0 (inclusive) to end 100 (not inclusive):
np.random.randint(0,100,20)

array([19, 18, 19, 77, 24,  8, 48, 86,  0, 46, 90, 94, 31,  0, 12, 53, 36,
       23, 31, 14], dtype=int32)

In [24]:
# to reshape the 20 random arry values in a 4x5 matrix
np.random.randint(0, 100, 20).reshape(4, 5)  # 4 rows, 5 columns

array([[91, 96, 85, 58, 53],
       [64, 63, 80, 90, 89],
       [73,  1, 74, 11, 60],
       [31, 90, 82, 99, 52]], dtype=int32)

In [26]:
#reshape function works on a np array object:
a = np.random.randint(0, 100, 20)
a.reshape(2,10)

array([[59,  6, 63, 77, 69, 94, 99, 63, 76, 23],
       [27, 82, 65, 32,  3, 15, 71, 62,  6, 11]], dtype=int32)

In [28]:
# direct 2d int array:
b=np.random.randint(0, 100, (4, 5))  # Generates a 4×5 matrix
b

array([[24, 26, 48,  4, 42],
       [31,  3, 98,  8, 20],
       [ 8,  0, 28,  0, 83],
       [60, 15, 78, 63, 84]], dtype=int32)

In [29]:
#finding the max value in a np array:
b.max()

np.int32(98)

In [30]:
# finding min value
b.min()

np.int32(0)

In [33]:
#locatin of max value:
max_loc = a.argmax()
max_loc
#locatin of min value:
min_loc = a.argmin()
min_loc

np.int64(14)

In [34]:
#find shape of an array:
b.shape

(4, 5)

In [35]:
#find datatype in an array:
b.dtype

dtype('int32')